create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.students (
  id text primary key,
  name text not null,
  class_name text not null,
  avatar text not null,
  type text check (type in ('Hafalan', 'Tartili')),
  current_juz integer,
  current_surah text not null,
  jenis_setoran text,
  iqra_level integer,
  page text,
  total_progress integer not null default 0,
  last_update text not null default 'Belum ada',
  last_score integer,
  status text not null check (status in ('Mumtaz', 'Jayyid Jiddan', 'Jayyid', 'Perlu Bimbingan')),
  notes text,
  requires_attention boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  id text primary key default 'default',
  academic_year jsonb not null default '{}'::jsonb,
  targets jsonb not null default '[]'::jsonb,
  teachers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null,
  note_date date not null default current_date,
  color text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.murojaah_entries (
  id bigint generated by default as identity primary key,
  juz integer not null default 30,
  surah text not null,
  status text not null check (status in ('completed', 'pending', 'upcoming')),
  entry_date text not null,
  score integer,
  type text not null check (type in ('individual', 'classical')),
  class_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists students_set_updated_at on public.students;
create trigger students_set_updated_at
before update on public.students
for each row
execute function public.set_updated_at();

drop trigger if exists app_settings_set_updated_at on public.app_settings;
create trigger app_settings_set_updated_at
before update on public.app_settings
for each row
execute function public.set_updated_at();

drop trigger if exists notes_set_updated_at on public.notes;
create trigger notes_set_updated_at
before update on public.notes
for each row
execute function public.set_updated_at();

drop trigger if exists murojaah_entries_set_updated_at on public.murojaah_entries;
create trigger murojaah_entries_set_updated_at
before update on public.murojaah_entries
for each row
execute function public.set_updated_at();

alter table public.students enable row level security;
alter table public.app_settings enable row level security;
alter table public.notes enable row level security;
alter table public.murojaah_entries enable row level security;

drop policy if exists "Allow public read students" on public.students;
create policy "Allow public read students"
on public.students for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write students" on public.students;
create policy "Allow public write students"
on public.students for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow public read app_settings" on public.app_settings;
create policy "Allow public read app_settings"
on public.app_settings for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write app_settings" on public.app_settings;
create policy "Allow public write app_settings"
on public.app_settings for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow public read notes" on public.notes;
create policy "Allow public read notes"
on public.notes for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write notes" on public.notes;
create policy "Allow public write notes"
on public.notes for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow public read murojaah_entries" on public.murojaah_entries;
create policy "Allow public read murojaah_entries"
on public.murojaah_entries for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write murojaah_entries" on public.murojaah_entries;
create policy "Allow public write murojaah_entries"
on public.murojaah_entries for all
to anon, authenticated
using (true)
with check (true);

-- New Gharib Table & Policies
create table if not exists public.jurnal_gharib (
  id bigint generated by default as identity primary key,
  class_name text not null,
  entry_date text not null,
  status text not null check (status in ('Lanjut', 'Mengulang')),
  material text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists jurnal_gharib_set_updated_at on public.jurnal_gharib;
create trigger jurnal_gharib_set_updated_at
before update on public.jurnal_gharib
for each row
execute function public.set_updated_at();

alter table public.jurnal_gharib enable row level security;

drop policy if exists "Allow public read jurnal_gharib" on public.jurnal_gharib;
create policy "Allow public read jurnal_gharib"
on public.jurnal_gharib for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write jurnal_gharib" on public.jurnal_gharib;
create policy "Allow public write jurnal_gharib"
on public.jurnal_gharib for all
to anon, authenticated
using (true)
with check (true);

-- New Setoran Table & Policies
create table if not exists public.setoran (
  id bigint generated by default as identity primary key,
  student_id text not null references public.students(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  type text not null check (type in ('Hafalan', 'Tartili')),
  current_surah text not null,
  current_juz integer,
  jenis_setoran text,
  iqra_level integer,
  page text,
  score integer,
  status text,
  notes text,
  requires_attention boolean not null default false,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists setoran_set_updated_at on public.setoran;
create trigger setoran_set_updated_at
before update on public.setoran
for each row
execute function public.set_updated_at();

alter table public.setoran enable row level security;

drop policy if exists "Allow public read setoran" on public.setoran;
create policy "Allow public read setoran"
on public.setoran for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write setoran" on public.setoran;
create policy "Allow public write setoran"
on public.setoran for all
to anon, authenticated
using (true)
with check (true);

-- New Attendance Table & Policies
create table if not exists public.attendance (
  id text primary key,
  student_id text not null references public.students(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  status text not null check (status in ('present', 'permission', 'sick', 'alpha')),
  attendance_date text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists attendance_set_updated_at on public.attendance;
create trigger attendance_set_updated_at
before update on public.attendance
for each row
execute function public.set_updated_at();

alter table public.attendance enable row level security;

drop policy if exists "Allow public read attendance" on public.attendance;
create policy "Allow public read attendance"
on public.attendance for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write attendance" on public.attendance;
create policy "Allow public write attendance"
on public.attendance for all
to anon, authenticated
using (true)
with check (true);

-- New Personal Messages Table & Policies
create table if not exists public.personal_messages (
  id bigint generated by default as identity primary key,
  student_id text not null references public.students(id) on delete cascade,
  student_name text not null,
  message text not null,
  status text not null check (status in ('Terkirim', 'Dibaca')) default 'Terkirim',
  message_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists personal_messages_set_updated_at on public.personal_messages;
create trigger personal_messages_set_updated_at
before update on public.personal_messages
for each row
execute function public.set_updated_at();

alter table public.personal_messages enable row level security;

drop policy if exists "Allow public read personal_messages" on public.personal_messages;
create policy "Allow public read personal_messages"
on public.personal_messages for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write personal_messages" on public.personal_messages;
create policy "Allow public write personal_messages"
on public.personal_messages for all
to anon, authenticated
using (true)
with check (true);

-- New Jurnal Tartili (Classical Schedule) Table & Policies
create table if not exists public.jurnal_tartili (
  id bigint generated by default as identity primary key,
  class_name text not null,
  entry_date text not null,
  status text not null check (status in ('Lanjut', 'Mengulang')),
  jilid text not null,
  start_page integer not null,
  end_page integer not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists jurnal_tartili_set_updated_at on public.jurnal_tartili;
create trigger jurnal_tartili_set_updated_at
before update on public.jurnal_tartili
for each row
execute function public.set_updated_at();

alter table public.jurnal_tartili enable row level security;

drop policy if exists "Allow public read jurnal_tartili" on public.jurnal_tartili;
create policy "Allow public read jurnal_tartili"
on public.jurnal_tartili for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write jurnal_tartili" on public.jurnal_tartili;
create policy "Allow public write jurnal_tartili"
on public.jurnal_tartili for all
to anon, authenticated
using (true)
with check (true);


-- New Ujian Tartili (Exam Schedule) Table & Policies
create table if not exists public.ujian_tartili (
  id bigint generated by default as identity primary key,
  student_id text not null references public.students(id) on delete cascade,
  student_name text not null,
  class_name text not null,
  jilid_asal integer not null,
  target_jilid text not null,
  hari_ujian text not null,
  tanggal_ujian text not null,
  jam_pelajaran text not null,
  penguji text not null,
  status text not null check (status in ('Terjadwal', 'Selesai', 'Batal')) default 'Terjadwal',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists ujian_tartili_set_updated_at on public.ujian_tartili;
create trigger ujian_tartili_set_updated_at
before update on public.ujian_tartili
for each row
execute function public.set_updated_at();

alter table public.ujian_tartili enable row level security;

drop policy if exists "Allow public read ujian_tartili" on public.ujian_tartili;
create policy "Allow public read ujian_tartili"
on public.ujian_tartili for select
to anon, authenticated
using (true);

drop policy if exists "Allow public write ujian_tartili" on public.ujian_tartili;
create policy "Allow public write ujian_tartili"
on public.ujian_tartili for all
to anon, authenticated
using (true)
with check (true);


